version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file:
      - ./api/.env.docker
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
      - worker

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - ./frontend/.env.docker
    ports:
      - "8001:8001"
    depends_on:
      - api

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./api/.env.docker

  test:
    build:
      context: .
      dockerfile: api/Dockerfile.test
    env_file:
      - ./api/.env.test
    depends_on:
      - db
      - rabbitmq
      - worker

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
  
  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    env_file:
      - ./api/.env.docker
    depends_on:
      - rabbitmq

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/ssl/private:/etc/ssl/private
    depends_on:
      - frontend

volumes:
  postgres_data:
