version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file:
      - ./api/.env.docker
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - ./frontend/.env.docker
    ports:
      - "8001:8001"
    depends_on:
      - api

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./api/.env.docker

  test:
    build:
      context: .
      dockerfile: api/Dockerfile.test
    env_file:
      - ./api/.env.test
    depends_on:
      - db

volumes:
  postgres_data:
