from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from alembic.operations import BatchOperations
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40ee230dcf92'
down_revision: Union[str, None] = '4fad494119cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('booking_id', sa.Integer(), nullable=True),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'),
                              nullable=True, server_default='PENDING'),
                    sa.Column('timestamp', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
                    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_bookings_payment_id', 'payments', ['payment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bookings_payment_id', type_='foreignkey')
        batch_op.drop_column('payment_id')

    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
