"""Add capacity to session

Revision ID: 52ba21cf3b45
Revises: b435cbec1435
Create Date: 2024-06-09 00:48:24.231384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ba21cf3b45'
down_revision: Union[str, None] = 'b435cbec1435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'capacity')
    # ### end Alembic commands ###
